### ISSUE TITLE
In hmac  hmacsha-256.mpcl the generated result is not same as the one genearted online using same credentials

### ISSUE THREAD

**Issue by iamfaiz123** [markkurossi/mpc#16]
while trying the code.
i used the key given in the example ie - b598163d740b0973b8b312881bfe6601e031d33d9f15be97b0cc8898ae570932fd755ced0af309f7625f531ab01cdc0ba7130ae14b561b905f53777255174170

and the message - Hello, world!...................
the Hmac sha256 output i got online is - 8b8252a526ca8b895cd3d7749124b9d801f654fa8a4a9d515b101468de48edde which does not matches with the one result[0] in the docs
expected result - Result[0]: 60d27dbd14f1e351f20069171fead00ef557d17ac9a41d02baa488ca4b90171a

notes-
site used for computing sha256
https://www.devglan.com/online-tools/hmac-sha256-online

**Comment by markkurossi** [comment]
I created the test values with Go's `crypto/sha256` and `hmac` packages:

```
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"

	"crypto/hmac"
)

func main() {
	key, err := hex.DecodeString("b598163d740b0973b8b312881bfe6601e031d33d9f15be97b0cc8898ae570932fd755ced0af309f7625f531ab01cdc0ba7130ae14b561b905f53777255174170")
	if err != nil {
		fmt.Print(err)
		return
	}
	fmt.Printf("key : %x\n", key)

	// 32 bytes of message
	msg := []byte("Hello, world!...................")
	fmt.Printf("msg : %x\n", msg)

	mac := hmac.New(sha256.New, key[:])
	mac.Write(msg)
	sum := mac.Sum(nil)
	fmt.Printf("sum : %x\n", sum)
}
```
and they return the same values as the MPC program:

```
key : b598163d740b0973b8b312881bfe6601e031d33d9f15be97b0cc8898ae570932fd755ced0af309f7625f531ab01cdc0ba7130ae14b561b905f53777255174170
msg : 48656c6c6f2c20776f726c64212e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e
sum : 60d27dbd14f1e351f20069171fead00ef557d17ac9a41d02baa488ca4b90171a
```
I checked the site you linked. It looks like it uses the key as ASCII string i.e. it is not decoding it as a hex-encoded value. With the values above, it gives me `5474050a2f93194eb8ad2a077417f5a51ad73181e9225ba512388539ad6da9cb`.

If I change the sample Go program to create the key as:
```
key = []byte("b598163d740b0973b8b312881bfe6601e031d33d9f15be97b0cc8898ae570932fd755ced0af309f7625f531ab0")
```
I get the same result as the online tool:
```
key : 623539383136336437343062303937336238623331323838316266653636303165303331643333643966313562653937623063633838393861653537303933326664373535636564306166333039663736323566353331616230
msg : 48656c6c6f2c20776f726c64212e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e
sum : 5474050a2f93194eb8ad2a077417f5a51ad73181e9225ba512388539ad6da9cb
```
