### ISSUE TITLE
help: Possible to implement 3 party MPC?

### ISSUE THREAD

**Issue by xomexh** [markkurossi/mpc#18]
Is it possible to implement a solution with a setup of one garbler and two evaluator, where each garbler has a 2-pc connection with each of the two evaluators, with the help of this library?

Can you give some insight on this?

**Comment by markkurossi** [comment]
Sorry the slow response. The library has no direct support for your setup. But you could run separate pairs of garbler/evaluator between each 2-party pair. I also started working on n-party protocol (n>2) so the network could run the computation with n>2 peers. But this protocol requires still more work.

**Comment by xomexh** [comment]
Thank you so much for the response Mark. As you mentioned, we are running separate pairs of 2-party pairs, and it works fine.
